# Generated by Django 6.0.7 on 2026-07-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_department_citizenfeedback_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfeedback',
            name='action_plan',
            field=models.TextField(blank=True),
        ),
    ]
