# Generated by Django 6.0.7 on 2026-08-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_citizenfeedback_action_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['county__name', 'name']},
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='ward',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='feedback.county'),
        ),
        migrations.AlterUniqueTogether(
            name='ward',
            unique_together={('county', 'name')},
        ),
    ]
