# Generated by Django 6.0.7 on 2026-08-05 18:06

from django.db import migrations

KENYA_COUNTIES = [
    "Mombasa", "Kwale", "Kilifi", "Tana River", "Lamu", "Taita-Taveta",
    "Garissa", "Wajir", "Mandera", "Marsabit", "Isiolo", "Meru",
    "Tharaka-Nithi", "Embu", "Kitui", "Machakos", "Makueni", "Nyandarua",
    "Nyeri", "Kirinyaga", "Murang'a", "Kiambu", "Turkana", "West Pokot",
    "Samburu", "Trans Nzoia", "Uasin Gishu", "Elgeyo-Marakwet", "Nandi",
    "Baringo", "Laikipia", "Nakuru", "Narok", "Kajiado", "Kericho",
    "Bomet", "Kakamega", "Vihiga", "Bungoma", "Busia", "Siaya", "Kisumu",
    "Homa Bay", "Migori", "Kisii", "Nyamira", "Nairobi",
]

WARDS_PER_COUNTY = 8


def seed_counties_and_wards(apps, schema_editor):
    County = apps.get_model("feedback", "County")
    Ward = apps.get_model("feedback", "Ward")

    counties_by_name = {}
    for name in KENYA_COUNTIES:
        county, _ = County.objects.get_or_create(name=name)
        counties_by_name[name] = county

    # Existing wards (Changamwe, Nyali, Kisauni, Likoni) predate the County
    # link and are real Mombasa wards - attach them there.
    mombasa = counties_by_name["Mombasa"]
    Ward.objects.filter(county__isnull=True).update(county=mombasa)

    # Fill every county up to WARDS_PER_COUNTY with placeholder wards so the
    # UI has something to select nationwide. These generated names are not
    # official ward names.
    for county in counties_by_name.values():
        existing_count = Ward.objects.filter(county=county).count()
        for i in range(existing_count + 1, WARDS_PER_COUNTY + 1):
            Ward.objects.get_or_create(county=county, name=f"Ward {i}")


def unseed_counties_and_wards(apps, schema_editor):
    County = apps.get_model("feedback", "County")
    Ward = apps.get_model("feedback", "Ward")

    # Only remove the generated placeholder wards and counties; leave
    # Mombasa and its original (real, pre-existing) wards untouched since
    # CitizenFeedback rows may reference them.
    Ward.objects.filter(name__startswith="Ward ").delete()
    County.objects.filter(name__in=KENYA_COUNTIES).exclude(name="Mombasa").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_county_alter_ward_options_alter_ward_name_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_counties_and_wards, unseed_counties_and_wards),
    ]
