# Generated by Django 6.0.7 on 2026-08-06 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_seed_counties_and_wards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfeedback',
            name='priority_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Declined', 'Declined')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
