# Generated by Django 6.0.7 on 2026-08-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_citizenfeedback_priority_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfeedback',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocated in KES.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='decision_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='estimated_completion',
            field=models.CharField(blank=True, help_text="Free-form timeframe, e.g. '3 months', 'Q2 2027'.", max_length=100),
        ),
        migrations.AddField(
            model_name='citizenfeedback',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citizenfeedback',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Resolved', 'Resolved'), ('Declined', 'Declined')], default='Open', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff'), ('admin', 'Admin'), ('official', 'Government Official')], default='guest', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
